### ISSUE TITLE
Windows: FilePath in pattern.conf.json with wrong format

### ISSUE THREAD

**Issue by PerOve** [StfBauer/generator-simplestyle#7]
Hi Stefan. Awesome work. I use Windows 10 and vscode.

When I add a new hbs file under one of the _patterns catalog, the _config\pattern.conf.json file is modified with the new file.

The filepath is formated like this:
"filepath" :  "atoms\\02-my-second-atom.hbs"

It should be like this:
"filepath" :  "atoms/02-my-second-atom.hbs"

I did correct the filepath manually.
But when I added a new hbs, both the new one and the old one got the wrong format.

**Comment by StfBauer** [comment]
Hi @PerOve,

good catch. Retested it now on Windows and fixed several issues that I spotted. Also added a middleware to allow CORS requests. I should now be Version 0.3.0.

Blog post is coming out.
If you find another issue please feel free to tell me.

Thanx once again.
/Stefan

**Comment by StfBauer** [comment]
@PerOve Close this issue for now. Please reopen if still exists on your machine.
