### ISSUE TITLE
no proper layout right after installing

### ISSUE THREAD

**Issue by shurick81** [StfBauer/generator-simplestyle#8]
I have done following sequence:

npm install -g generator-simplestyle bower gulp jslint
cd <dir>
yo simplestyle
gulp serve

I can see strange picture in both Edge in Chrome:
![image](https://cloud.githubusercontent.com/assets/11289124/24346754/6df1aa3a-12de-11e7-82ba-5cd9c5a132a9.png)

I expected to see some menu, but maybe I just should change something in the project before I run serve?

The DOM that I've got in browser:

```
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>helloworldsimplestyle</title>
    <!-- bower:css -->
    <!-- endbower -->
    <link href="/styles/ssgCore.css" type="text/css" rel="stylesheet">
    <!-- <link href="/styles/prism.css" type="text/css" rel="stylesheet"> -->
    <link href="/styles/corev15.css" type="text/css" rel="stylesheet">
    <link href="/styles/main.css" type="text/css" rel="stylesheet">
    <!-- build:js scripts/vendor/modernizr.js -->
    <!-- endbuild -->
    <!-- inject:css -->
    <!-- endinject -->
</head>

<body class='ssg-body' id="ssg-font"><script id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.js?v=2.18.8'><\/script>".replace("HOST", location.hostname));
//]]></script>

    <div id="ssg-toolbar">
        <div id="ssg-toc" class="ssg-toc-list"></div>
        <div id="ssg-filter" class="ssg-cmd-section"></div>
        <div id="ssg-vp-resizer" class="ssg-cmd-section"></div>
        <div id="ssg-add-tools" class="ssg-cmd-section"></div>
        <div id="ssg-item-selector" class="ssg-cmd-section"></div>
    </div>
    <div id="ssg-wrapper">
        <div id='ssg-patterns' class="ssg-patterns">
            <div id="ssg-patterns-inner" class="ssg-patterns-inner"></div>
        </div>
    </div>
    <!-- bower:js -->
    <script src="/bower_components/handlebars/handlebars.js"></script>
    <!-- endbower -->
    <script src="/scripts/main.js"></script>
    <!-- inject:js -->
    <!-- <script src="/scripts/prism.js"></script> -->
    <script src="/scripts/ssg.templates.js"></script>
    <script src="/scripts/ssgCore.templates.js"></script>
    <script src="/scripts/ssgCoreLib.js"></script>
    <!-- endinject -->
</body>

</html>
```

**Comment by StfBauer** [comment]
The problem is the certificate error in your browser. You need to trust the certificate.
After that the user interface should load normal.

**Comment by shurick81** [comment]
Hi Stefan,

I have installed certificate to root, but the result is the same. I also noticed errors in console:

![image](https://cloud.githubusercontent.com/assets/11289124/24354551/ec71011e-12fa-11e7-8002-00441e747b4d.png)

**Comment by StfBauer** [comment]
What NodeJS version you are using? To get it `node --version`
Can you run `bower install` on the console?

**Comment by shurick81** [comment]
nodejs version is v6.8.0.
No, I hadn't run bower install before you said.
I tried to run "bower install" in nodejs in project folder but it changed nothing so far.

**Comment by StfBauer** [comment]
I tested this out now and it seems that some of your dependencies are outdated. In general I used the NodeJS Version 4.x.x for a long time.
Now I upgrade to node version v6.10.1.
The following packages and versions are now installed in the project folder:
```
├── browser-sync@2.18.8
├── chalk@1.1.3
├── del@2.2.2
├── gulp@3.9.1
├── gulp-autoprefixer@3.1.1
├── gulp-concat@2.6.1
├── gulp-declare@0.3.0
├── gulp-handlebars@4.0.0
├── gulp-if@2.0.2
├── gulp-inject@4.2.0
├── gulp-jscs@4.0.0
├── gulp-jshint@2.0.4
├── gulp-load-plugins@1.5.0
├── gulp-merge@0.1.1
├── gulp-plumber@1.1.0
├── gulp-print@2.0.1
├── gulp-rename@1.2.2
├── gulp-sass@2.3.2
├── gulp-sourcemaps@2.4.1
├── gulp-util@3.0.8
├── gulp-watch@4.3.11
├── gulp-wiredep@0.0.0
├── gulp-wrap@0.13.0
├── handlebars@4.0.6
├── jshint@2.9.4
├── jshint-stylish@2.2.1
├── merge-stream@1.0.1
├── npm@3.10.10
├── rename@1.0.4
├── stream-browserify@2.0.1
├── through2@2.0.3
├── wiredep@4.0.0
└── yargs@6.6.0
```
In addition you can try `gulp wiredep` and see if you have any issues running this command.

Thank you for all your testing.

**Comment by shurick81** [comment]
Hi, no worries, I'm determined to get it working.

I've now upgraded to v6.10.1 as well.
I've created new empty folder, then:
```
yo simplestyle
? Should folders for atomic design be created? Yes
```

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
bower prism#^1.5.1              ENOGIT git is not installed or not in the PATH
```
`gulp serve
`
As a result I can see the same page without top menu.
The same 404 error in javascript console
Here is what I've got for `gulp wiredep`:
```
[20:11:28] Using gulpfile D:\Alex\LocalDev\helloworldsimplestyle2\gulpfile.js
[20:11:28] Starting 'wiredep'...
[20:11:28] Finished 'wiredep' after 61 ms
[20:11:28] app\styles\main.scss
[20:11:28] Plumber found unhandled error:
 Error: Error: Cannot find where you keep your Bower packages.
[20:11:28] app\index.html
[20:11:28] Plumber found unhandled error:
 Error: Error: Cannot find where you keep your Bower packages.
```

Then I've then tried 
`? Should folders for atomic design be created? No
`
with the same result for page layout, console errors and `gulp wiredep`

**Comment by StfBauer** [comment]
Can you ```npm install -g bower``` and then ```npm install bower```.
After the you should execute ```gulp wiredep``` again.

Keen to see how this will end up.

**Comment by shurick81** [comment]
```
D:\Alex\LocalDev\helloworldsimplestyle2>npm install -g bower
C:\Users\alexa\AppData\Roaming\npm\bower -> C:\Users\alexa\AppData\Roaming\npm\node_modules\bower\bin\bower
C:\Users\alexa\AppData\Roaming\npm
`-- bower@1.8.0


D:\Alex\LocalDev\helloworldsimplestyle2>npm install bower
simplestyle@0.0.1 D:\Alex\LocalDev\helloworldsimplestyle2
`-- bower@1.8.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

D:\Alex\LocalDev\helloworldsimplestyle2>gulp wiredep
[20:24:53] Using gulpfile D:\Alex\LocalDev\helloworldsimplestyle2\gulpfile.js
[20:24:53] Starting 'wiredep'...
[20:24:53] Finished 'wiredep' after 62 ms
[20:24:53] app\styles\main.scss
[20:24:53] Plumber found unhandled error:
 Error: Error: Cannot find where you keep your Bower packages.
[20:24:53] app\index.html
[20:24:53] Plumber found unhandled error:
 Error: Error: Cannot find where you keep your Bower packages.
```

**Comment by StfBauer** [comment]
Do you have a '.bowerrc' file in your directory?

This file should contain the following informations:
```
{
    "directory": "bower_components",
    "scripts": {
        "postinstall": "gulp wiredep"
    }
}
```

**Comment by shurick81** [comment]
yes, it contains exactly what you suggest

**Comment by StfBauer** [comment]
Even bower_components folder exists?

**Comment by shurick81** [comment]
There is no such folder in the project

**Comment by StfBauer** [comment]
After I upgrade today to version 6.10.1 I had the exact same issue on another project that is not based on simplestyle. In my case I was able to fix it.

What I did was:

1.) ```npm install -g bower```

2.) ```npm install bower``` installed in project folder

3.) ```bower install``` - installed add bower components and created folder bower_components

4.) ```gulp wiredep```

After that I was able to start the project normal via ```gulp serve```

Strangely haven't had this issue with simplestyle.

**Comment by shurick81** [comment]
so when I "bower install", folder should be created automatically? Then probably it's not something in "simplestyle"?

**Comment by StfBauer** [comment]
The .bowerrc file will be used to create the folder 'bower_components' because it is there configured as the 'directory'.
The information to install bower components will be taken from the bower.json file. This is similar to the package.json of the npm packages.

Also make sure the 'bower.json' file has the following content.
````
{
    "name": "simplestyle",
    "description": "Simple Style Guide Tool based on Atomic Web Design",
    "authors": [
        "Stefan Bauer"
    ],
    "license": "MIT",
    "keywords": [
        "Atomic",
        "Design",
        "Style",
        "Guide",
        "Web",
        "Desgin",
        "Pattern",
        "UI",
        "UX"
    ],
    "homepage": "https://github.com/StfBauer/SimpleStyle",
    "moduleType": [
        "node"
    ],
    "private": true,
    "dependencies": {
        "modernizer": "~2.8.2",
        "handlebars": "~4.0.5",
        "prism": "^1.5.1"
    }
}
```

**Comment by shurick81** [comment]
bower.json file contents is exactly the same you suggest.
Bewildering. I think I should ask help in Bower community.

**Comment by StfBauer** [comment]
@shurick81 please let me know what they found out. Would be really interested what the reason might be. Though on changing it to native npm in an upcoming release.

**Comment by shurick81** [comment]
I've noticed error when I run
```
D:\Alex\LocalDev\hwss4>bower install
bower modernizer#~2.8.2         ENOGIT git is not installed or not in the PATH

```
After installing git https://git-for-windows.github.io/ package was built correctly:

![image](https://cloud.githubusercontent.com/assets/11289124/24477113/83734fd8-14de-11e7-9791-3c5b79455304.png)

**Comment by StfBauer** [comment]
Oh nice! Must have overlook this thing. Yes that can cause the issue because bower downloads their components using ```git clone```.

Thanks for the heads up and please feel free to ask me if you need assistance or have some suggestions.
